[2024-05-31T13:31:34.462+0000] {processor.py:161} INFO - Started process (PID=50) to work on /opt/airflow/dags/test.py
[2024-05-31T13:31:34.463+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-31T13:31:34.463+0000] {logging_mixin.py:188} INFO - [2024-05-31T13:31:34.463+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-31T13:31:34.478+0000] {logging_mixin.py:188} INFO - [2024-05-31T13:31:34.476+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 23, in <module>
    with DAG(DAG_ID,
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 580, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2024-05-31T13:31:34.479+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-31T13:31:34.491+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.031 seconds
[2024-05-31T13:32:04.634+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/test.py
[2024-05-31T13:32:04.635+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-31T13:32:04.635+0000] {logging_mixin.py:188} INFO - [2024-05-31T13:32:04.635+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-31T13:32:04.656+0000] {logging_mixin.py:188} INFO - [2024-05-31T13:32:04.651+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 23, in <module>
    with DAG(DAG_ID,
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 580, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2024-05-31T13:32:04.658+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-31T13:32:04.667+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.036 seconds
